var str='harry';
console.log("---------------to uppercase-----------------");
var s1=str.toUpperCase();
console.log(s1);
console.log("---------------to lowercase-----------------");
var s2=str.toLowerCase();
console.log(s2);
console.log("---------------for perticular char-----------------");
var s3=str.charAt(2);
console.log(s3);
console.log("---------------to find index-----------------");
var s4=str.indexOf('p',2);
console.log(s4);
console.log("----------------to concatenate----------------");
var s5=str.concat('potter');
console.log(s5);
console.log("----------------check wheather it is included in string----------------");
var s6=str.includes('e',0);
console.log(s6);
console.log("--------------replace the give str to old str------------------");
var s7=str.replace('ha','ma');
console.log(s7);
console.log("---------------splits the string and gives as array-----------------");
var s8=str.split();
console.log(s8);
console.log("----------------splits the string and gives as array----------------");
var s9=str.split('p',2);
console.log(s9);
console.log("---------------creat another str within give range-----------------");
var s10=str.substr(0,3);
console.log(s10);
console.log("---------------search the chr in str-----------------");
var s11=str.search('l');
console.log(s11);
console.log("----------------removes the gap----------------");
var string=              'pooja';
var s12=string.trim();
console.log(s12);
console.log("--------------------------------------------------------------------------------------------");

console.log("------------------------------------------example 2--------------------------------------------------");

var str='happy';
console.log("---------------to uppercase-----------------");
var s1=str.toUpperCase();
console.log(s1);
console.log("---------------to lowercase-----------------");
var s2=str.toLowerCase();
console.log(s2);
console.log("---------------for perticular char-----------------");
var s3=str.charAt(2);
console.log(s3);
console.log("---------------to find index-----------------");
var s4=str.indexOf('p',2);
console.log(s4);
console.log("----------------to concatenate----------------");
var s5=str.concat('family');
console.log(s5);
console.log("----------------check wheather it is included in string----------------");
var s6=str.includes('e',0);
console.log(s6);
console.log("--------------replace the give str to old str------------------");
var s7=str.replace('happy','enjoying');
console.log(s7);
console.log("---------------splits the string and gives as array-----------------");
var s8=str.split();
console.log(s8);
console.log("----------------splits the string and gives as array----------------");
var s9=str.split('p',2);
console.log(s9);
console.log("---------------creat another str within give range-----------------");
var s10=str.substr(0,3);
console.log(s10);
console.log("---------------search the chr in str-----------------");
var s11=str.search('l');
console.log(s11);
console.log("----------------removes the gap----------------");
var string=              'pooja';
var s12=string.trim();
console.log(s12);
console.log("--------------------------------------------------------------------------------------------");

